# Generated by Django 4.0 on 2021-12-30 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('title', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ICD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_code', models.CharField(blank=True, max_length=5)),
                ('full_code', models.CharField(blank=True, max_length=15)),
                ('abbreviated_description', models.TextField(max_length=100)),
                ('full_description', models.TextField(max_length=233)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icd10.category')),
            ],
            options={
                'verbose_name': 'ICD',
            },
        ),
    ]
