# Generated by Django 4.0 on 2022-01-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icd10', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icd',
            name='full_code',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
