# Generated by Django 4.0 on 2022-03-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icd10', '0005_alter_icd_full_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icd',
            name='full_code',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
